image:
  file: .gitpod.Dockerfile

tasks:
  - name: Redis
    before: printf "\n[settings]\napi_key = $WAKA_TIME_API_KEY\n" > ~/.wakatime.cfg
    command: redis-server
    openMode: split-right
  - name: FastAPI
    init: pip install -r requirements.txt
    command: uvicorn app.main:app --reload

vscode:
  extensions:
    - github.vscode-pull-request-github
    - redhat.vscode-yaml
    - vivaxy.vscode-conventional-commits
    - mhutchie.git-graph
    - oderwat.indent-rainbow
    - christian-kohler.path-intellisense
    - esbenp.prettier-vscode
    - vscode-icons-team.vscode-icons
    - wakatime.vscode-wakatime
    - qcz.text-power-tools
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-azuretools.vscode-docker
    - alexcvzz.vscode-sqlite